// Generated by Selenium IDE
package selenium;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class DefaultSuiteTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void a() throws InterruptedException{
    driver.get("https://github.com/");
    driver.manage().window().setSize(new Dimension(1024, 736));
    driver.findElement(By.linkText("Sign in")).click();
    driver.findElement(By.id("login_field")).click();
    driver.findElement(By.id("login_field")).sendKeys("seleniumtest-123");
    driver.findElement(By.id("password")).sendKeys("");
    driver.findElement(By.name("commit")).click();
    driver.findElement(By.linkText("Create a repository")).click();
    driver.findElement(By.id("repository_name")).click();
    driver.findElement(By.id("repository_name")).sendKeys("abc");
    Thread.sleep(5000);
    driver.findElement(By.xpath("(//button[@type=\'submit\'])[3]")).click();
    driver.findElement(By.linkText("creating a new file")).click();
    driver.findElement(By.name("filename")).click();
    driver.findElement(By.name("filename")).sendKeys("hello.py");
    driver.findElement(By.cssSelector(".code")).click();
    driver.findElement(By.cssSelector(".CodeMirror-scroll")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".CodeMirror-code"));
      js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<div style=\"position: relative;\"><div class=\"CodeMirror-gutter-wrapper\" contenteditable=\"false\" style=\"left: -53px;\"><div class=\"CodeMirror-linenumber CodeMirror-gutter-elt\" style=\"left: 0px; width: 21px;\">1</div></div><pre class=\" CodeMirror-line \" role=\"presentation\"><span role=\"presentation\" style=\"padding-right: 0.1px;\">print(\"hello\")</span></pre></div>'}", element);
    }
    driver.findElement(By.id("submit-file")).click();
    driver.findElement(By.linkText("seleniumtest-123")).click();
  }
}
